# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 731db6a09c20a861c809ea530669f1361fec0e35c0dc9a7035fad561ae7db761280e50aee8d27b6ff6caed8d29e17cef593e83eeb052278468b18cf134e59faf

test:
  secret_key_base: 92ef8ffc094a802b9b59a619b502df7dfa6973a5d31e39df810f0cd5c6e7c5bab60c4254565f3eb7203ee6d421b7aef60b768a24737d49959161b18327d32ade

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
